name : Panji Belajar Deploy 
on:
  push:
    branches: [ develop ]

jobs:
  first:
    name: Pull from github
    runs-on: ubuntu-latest
    steps:
    - name: test deploy dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_KRIS }}
        username: root
        key: ${{ secrets.MY_KEY }}
        port: ${{ secrets.PORTO }}
        script: |
          cd /home/admin/web/dev.panjibaskoro.web.id/public_html
          git pull origin develop